### ISSUE TITLE
The Human Brain and Logic if this happens do x

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/sinatra-intro-to-mvc#10]
At what point does something happen and our brains make a decision?  How do we know to make that decision?  It comes from experience and a set of beliefs.  But all of that exists only from our memories which are like databases.  So for a human being what would be the controller?  It would be a part of the brain or a set of decisions maybe?  My point is that logic lives in the brain.  The brain is on so it's a constant state.  It doesn't stop thinking until your dead.  

So to make an example of MVC saying that the model is the brains doesn't really hold true.  Think of the brain as RAM.  It's Read and Write memory not a hard drive or database although memory can hold entities from these things in an on state.

So the MVC is a giant Brain and the View becomes the response.  So It's like two human beings interacting Person A says 'foobar' and Person B hears 'foobar' (the request) and processes it through a set of beliefs\experiences (the database).  Person B doesn't know what 'foobar' means and responds with a confused look.  Now that's a view. =P

So It's reasonable to say that the model isn't the brain of a program.  Lets be explicit and call a model what it is.  Information\Business Information organized in a logical way.

**Comment by PeterBell** [comment]
Hey @genericlady please feel free to submit a PR with some specific language changes and I'll run them by the curriculum team, but again I'm not sure the analogy is unreasonable. Like most analogies it is useful up to a point
