### ISSUE TITLE
Image Broken

### ISSUE THREAD

**Issue by littlejeon** [learn-co-curriculum/sinatra-intro-to-mvc#6]
The "Model-View-Controller" is not showing up

**Comment by AnnJohn** [comment]
Hi @littlejeon do you mean the video? I believe there isn't an image in this lesson. Thanks

**Comment by littlejeon** [comment]
[image: Inline image 1]
This is what I get under "Model-View-Controller"

On Wed, Dec 23, 2015 at 9:53 AM, AnnJohn <notifications@github.com> wrote:

> Hi @littlejeon <https://github.com/littlejeon> do you mean the video? I
> believe there isn't an image in this lesson. Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/sinatra-intro-to-mvc/issues/6#issuecomment-166916507>
> .
>



-- 
-Lisa

**Comment by AnnJohn** [comment]
Hi @littlejeon the image didn't come through. Could you resend? Thanks

**Comment by littlejeon** [comment]
[image: Inline image 1]
Sure here you go!

On Wed, Dec 23, 2015 at 11:11 AM, AnnJohn <notifications@github.com> wrote:

> Hi @littlejeon <https://github.com/littlejeon> the image didn't come
> through. Could you resend? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/sinatra-intro-to-mvc/issues/6#issuecomment-166933675>
> .
>



-- 
-Lisa

**Comment by AnnJohn** [comment]
Should be fixed now!

**Comment by littlejeon** [comment]
thank you!

On Tue, Dec 29, 2015 at 10:02 AM, AnnJohn <notifications@github.com> wrote:

> Closed #6
> <https://github.com/learn-co-curriculum/sinatra-intro-to-mvc/issues/6>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/sinatra-intro-to-mvc/issues/6#event-502150070>
> .
>



-- 
-Lisa
